import { Geist, Geist_Mono, Bellefair, Barlow_Condensed, Barlow } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const bellefair = Bellefair({
  variable: "--font-bellefair",
  subsets: ["latin"],
  weight: ["400"],
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlowcondensed",
  subsets: ["latin"],
  weight: ["400"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${barlowCondensed.variable} ${barlow.variable} ${bellefair.variable} antialiased font-bellefair text-white`}
      >
                
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
