import Image from "next/image";
import AnimatedRound from "./components/AnimatedRound";

export const metadata = {
  title: "Space Tourism - Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="bg-[url(/home/background-home-mobile.jpg)] md:bg-[url(/home/background-home-tablet.jpg)]
                    lg:bg-[url(/home/background-home-desktop.jpg)] bg-cover
                    w-full h-screen flex justify-center items-end text-white overflow-hidden">
      <div className="flex flex-col lg:flex-row items-center lg:items-end justify-end lg:pb-[10%] px-10 md:px-20">
        <div className="flex flex-col items-center justify-center lg:w-1/2 text-left">          
          <h4 className="uppercase text-[20px] md:text-[28px] text-primary font-bellefair ">So, You Want to Travel to</h4>
          <h1 className="uppercase text-[100px] md:text-[144px] font-bellefair">Space</h1>          
          <p className="lg:w-2/3 text-primary font-barlow text-[18px] text-center"> Let’s face it; if you want to go to space, you might as well genuinely go to outer space and not hover kind of on the edge of it. Well sit back, and relax because we’ll give you a truly out of this world experience! Explore </p>
          
        </div>
        <div className="lg:w-1/2 flex items-center justify-center">
          <AnimatedRound/>

        </div>
      </div>
    </div>
  );
}
